<a href="https://colab.research.google.com/github/Saldon1986/Simulative_ML/blob/main/Simulative_ML_choising.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Сформируйте кластеризованную выборку из 20 пользователей из таблицы USERS так, чтобы в нее входили клиенты из 3 случайных компаний (company_id) в таких же пропорциях, как они представлены в генеральной совокупности.

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, date
import random

In [2]:
USERS = pd.read_csv('/content/itresume-users.csv', parse_dates=['date_joined'], date_format='%Y-%m-%d %H:%M:%S')

In [3]:
USERS.head(3)

    id       username         date_joined  company_id
0  416  nsosabisfsobm 2022-01-02 12:22:43           4
1   43    NbabnnbTona 2021-07-01 09:11:42          11
2   50           jbdn 2021-08-04 09:01:56           4

In [14]:
# проверим, что есть 20 записей по случайны компаниям
tot = 0
N = 20
while tot < N:
  # series of random companies
  comps = random.sample(USERS['company_id'].unique().tolist(), 3)

  # sampling
  DF = USERS[USERS['company_id'].isin(comps)]
  tot = DF['id'].count()

In [15]:
all_columns = USERS.columns.tolist()
users_sample = DF.groupby('company_id', group_keys=False)[all_columns].apply(lambda x: x.sample(int(np.rint(N*len(x)/len(DF)))), include_groups=False)

In [16]:
users_sample

     id         username         date_joined  company_id
94  861      KbaxsnDsnom 2022-01-27 17:02:21           8
38  273        obmbdonob 2021-11-29 13:31:51           8
82  551           ooxo32 2022-01-16 07:30:51           8
24  235       DskobAmfos 2021-11-25 16:20:59           8
42  278            nnofo 2021-11-30 16:13:38           8
10  217  fnoxonsnbkbxsnb 2021-11-24 16:05:45           8
72  411           oabxeo 2021-12-30 07:24:19           8
93  839         Bsffabb3 2022-01-26 23:23:19           8
8    93       cbensxxsnb 2021-11-19 20:36:11           8
66  361            Iakbn 2021-12-20 14:29:54           9
53  316            obxsn 2021-12-06 16:36:21           9
55  330     coonsdabnbmm 2021-12-11 13:29:56           9
79  444             Asob 2022-01-09 07:50:15           9
41  276           Sdbn1o 2021-11-30 03:46:54           9
59  351       Hbbisonbbi 2021-12-18 19:55:43           9
40  275          DokbnIT 2021-11-29 17:23:27          10
76  426             Dxfx 2022-01-05 09:49:58          10
67  381   VsabdssIbosnsn 2021-12-22 10:37:19          10
86  568           Dsksen 2022-01-17 06:12:27          10
83  556       fsbkbnaodf 2022-01-16 15:25:40          10
44  280      aonibidomsn 2021-11-30 17:52:53          10

Далее на основании этой кластерной выборки клиентов сформируйте стратифицированную выборку для таблицы CODERUN таким образом, чтобы в нее входило по 1 случайной строке для каждой даты (created_at).

In [85]:
CODE_RUN = pd.read_csv('/content/itresume-coderun.csv') #, parse_dates=['created_at'], date_format='%Y-%m-%d %H:%M:%S.%f')
CODE_RUN['created_at'] = pd.to_datetime(CODE_RUN['created_at'], format='%Y-%m-%d %H:%M:%S.%f').dt.date

In [86]:
CODE_RUN.head(3)

   id  created_at  problem_id  user_id  language_id
0   1  2021-04-07          13       10            3
1   2  2021-03-31          15       13            3
2   3  2021-04-04           1        6            3

In [87]:
CODE_RUN.columns

Index(['id', 'created_at', 'problem_id', 'user_id', 'language_id'], dtype='object')

In [88]:
# concat DFs

df_tot = users_sample.merge(CODE_RUN, how='inner', right_on='user_id', left_on='id')
df_tot.columns = ['user_id', 'username', 'date_joined', 'company_id', 'problem_id', 'created_at',
        'problem_id', 'user_id_todrop', 'language_id']
df_tot.drop('user_id_todrop', axis=1)

,user_id,username,date_joined,company_id,problem_id,created_at,problem_id,language_id
0,861,KbaxsnDsnom,2022-01-27 17:02:21,8,17541,2022-01-27,126,2
1,861,KbaxsnDsnom,2022-01-27 17:02:21,8,17542,2022-01-27,126,2
2,861,KbaxsnDsnom,2022-01-27 17:02:21,8,17546,2022-01-27,127,2
3,861,KbaxsnDsnom,2022-01-27 17:02:21,8,17547,2022-01-27,127,2
4,861,KbaxsnDsnom,2022-01-27 17:02:21,8,17549,2022-01-27,127,2
...,...,...,...,...,...,...,...,...
3733,280,aonibidomsn,2021-11-30 17:52:53,10,4472,2021-12-06,86,2
3734,280,aonibidomsn,2021-11-30 17:52:53,10,4473,2021-12-06,86,2
3735,280,aonibidomsn,2021-11-30 17:52:53,10,4474,2021-12-06,86,2
3736,280,aonibidomsn,2021-11-30 17:52:53,10,4475,2021-12-06,117,2
3737,280,aonibidomsn,2021-11-30 17:52:53,10,4476,2021-12-06,117,2

In [89]:
all_cols = df_tot.columns.to_list()
coderun_sample = df_tot.groupby('created_at', group_keys=False)[all_cols].apply(lambda x: x.sample(1))

In [90]:
coderun_sample

,user_id,username,date_joined,company_id,problem_id,problem_id,created_at,problem_id,problem_id,user_id_todrop,language_id
710,217,fnoxonsnbkbxsnb,2021-11-24 16:05:45,8,1566,117,2021-11-24,1566,117,217,2
711,217,fnoxonsnbkbxsnb,2021-11-24 16:05:45,8,1796,118,2021-11-25,1796,118,217,2
75,273,obmbdonob,2021-11-29 13:31:51,8,2920,118,2021-11-29,2920,118,273,2
3168,276,Sdbn1o,2021-11-30 03:46:54,9,3482,132,2021-12-01,3482,132,276,2
3328,276,Sdbn1o,2021-11-30 03:46:54,9,3713,141,2021-12-02,3713,141,276,2
...,...,...,...,...,...,...,...,...,...,...,...
2404,839,Bsffabb3,2022-01-26 23:23:19,8,54812,87,2022-05-13,54812,87,839,2
2424,839,Bsffabb3,2022-01-26 23:23:19,8,54906,240,2022-05-14,54906,240,839,3
2451,839,Bsffabb3,2022-01-26 23:23:19,8,55180,184,2022-05-15,55180,184,839,3
2493,839,Bsffabb3,2022-01-26 23:23:19,8,55640,191,2022-05-16,55640,191,839,3
2519,839,Bsffabb3,2022-01-26 23:23:19,8,55672,193,2022-05-17,55672,193,839,3